name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-build:
    name: Docker Image Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    -  name: Set up QEMU
       uses: docker/setup-qemu-action@v1
       
    -  name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
        
    -  name: Login to DockerHub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    -  name: Build and push
       uses: docker/build-push-action@v2
       with:
        context: .
        push: true
        tags: gorje6/django-demo-app:latest
        
###### Star scanning after image is built and pushed        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/gorje6/django-demo-app:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
